version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - dockerwp
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerwp
    restart: always
  app:
    container_name: api-v2-0.0.1
    image: api-v2-0.0.1
    build: ./
    expose:
      - 80
    environment:
      VIRTUAL_HOST: 'api.kpyvara.com'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'api.kpyvara.com'
      LETSENCRYPT_EMAIL: 'xavi@kpyvara.com'
    depends_on:
      - dbpostgresql-db
    networks:
      - dockerwp
    restart: always
  dbpostgresql-db:
    container_name: dbpostgresql-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: XaviNoob2016
      POSTGRES_USER: postgres
      POSTGRES_DB: sofia-db1
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - dockerwp
    restart: always
networks:
  dockerwp:
volumes:
  certs:
  html:
  vhostd: