version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - dockerwp
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockerwp
    restart: always
  app:
    container_name: api-v2-0.0.1
    image: api-v2-0.0.1
    build: ./
    expose:
      - 80
    environment:
      VIRTUAL_HOST: 'api.kpyvara.com'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'api.kpyvara.com'
      LETSENCRYPT_EMAIL: 'xavi@kpyvara.com'
    depends_on:
      - dbpostgresql-db
    networks:
      - dockerwp
    restart: always
  dbpostgresql-db:
    container_name: dbpostgresql-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: XaviNoob2016
      POSTGRES_USER: postgres
      POSTGRES_DB: sofia-db1
    volumes:
      - ./postgres-data:/var/lib/postgresql
    networks:
      - dockerwp
    restart: always
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./front:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=kpyvara.com,www.kpyvara.com
      - LETSENCRYPT_HOST=kpyvara.com,www.kpyvara.com
      - LETSENCRYPT_EMAIL=xavi@kpyvara.com
    networks:
      - dockerwp
    restart: always
  netdata:
    image: netdata/netdata:v1.19.0
    restart: always
    expose:
      - "19999"
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - netdata-etc:/etc/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    environment:
      - VIRTUAL_PORT=19999
      - DOCKER_HOST=proxy:2375
      - PGID=999
      - VIRTUALIZATION=kvm
      - VIRTUAL_HOST=metri.kpyvara.com,metri.kpyvara.com
      - LETSENCRYPT_HOST=metri.kpyvara.com,metri.kpyvara.com
      - LETSENCRYPT_EMAIL=xavi@kpyvara.com
  proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
networks:
  dockerwp:
volumes:
  certs:
  html:
  vhostd:
  netdata-etc:
